### PR TITLE
Statically allocate recursive_mutex to address issue #121

### PR DESCRIPTION
**Pull request by rollbear**
Would you please take a look and see if it solves the problem without causing too bad new ones.

@jktjkt does this work for you?

### CODE REVIEW

**Comment by AndrewPaxie** [comment]
Yes I will.  I've kept silent on this one since I discovered every I'd said before was based on
my many misunderstandings.

**Comment by rollbear** [comment]
No worries, but it's good to get an extra pair of eyes on it. As far as I've understood, it needs to be a very exotic system for the leaked recursive_mutex to cause problems, so I'm not really concerned there.

**Comment by rollbear** [comment]
Thank you. `aligned_storage´ is obviously what should be used. It's what it's there for.

I'm ignoring the `owner` issue for now.

clang-8 works fine.

**Comment by AndrewPaxie** [comment]
Should be good to go after Coveralls and Travis finish.

**Pull request merged**
