### PR TITLE
add runtime ``TIMES``

### PR DESCRIPTION
**Pull request by DNKpp**
as discussed in this issue https://github.com/rollbear/trompeloeil/issues/283 it would be very helpful to have the TIMES action configurable with runtime arguments.
This PR aims to add that, without making too much changes to existing symbols (in fact, no changes are made at all).

As this is mainly a sketchup for the actual feature, I'm open for feedback regarding behavior and naming (maybe ``RT_TIMES is a more appropriate name).

### CODE REVIEW

**Comment by DNKpp** [comment]
These detected memory leaks seem to be caused by the exception thrown from the ``dynamic_times`` constructor. But that's not the root cause of the issue, as ``trompeloeil`` surprisingly has a very poor resource managing (e.g. the matcher is "forwarded" via raw pointer).

**Comment by rollbear** [comment]
From a very brief glance, this looks interesting. I'm away on a conference right now, but I'll have a closer look when I get back home again.

**Comment by rollbear** [comment]
This is looking really neat. Thank you. Is there something you want to discuss, given that it's still marked [WIP]?

Otherwise, I think it's just a matter of adding docs and negative test(s) under 'compilation_errors' before I can merge it.

Naming can always be discussed, but I think DYN_TIMES is as good as anything I can come up with.

**Comment by rollbear** [comment]
Ping! I know I haven't been very attentive lately, but I hope to be able to tag a release in the tear future, say during the weekend July 13-14th. If there are things you want from me to be able to merge this, then let me know. As mentioned before, I'm cool with the change and the names, but would appreciate docs and some more tests.

**Comment by DNKpp** [comment]
Hey, sry for the delay. I'm currently very busy with my thesis, so I won't have much spare time for this during the next month or so.

I'm not sure, which tests I should add, as I mostly reuse existing components and already added a couple of tests. The negative tests are in the section beginning at 4835. Sure, we could explicitly add some constexpr tests, which will not compile with invalid bounds (because of the exception), but I don't think that would be of much value.

I would really like to rename it to ``RT_TIMES`` as this seems to me to be more in line with the rest of the framework (which already uses the 2 sign prefixes for other features).

**Comment by rollbear** [comment]
Ok, no worries. There's no hurry.

**Comment by DNKpp** [comment]
Hey, I finally got the time to invest some time into this feature.
I renamed it to ``RT_TIMES`` and added some compilation error files. Are they ok?

**Comment by DNKpp** [comment]
So, I think I'm done. Added the necessary documentation and checked, that all anchors are working as expected. Don't know why codecov now started complaining.

**Comment by rollbear** [comment]
Never mind codecov. It's being silly. I'll have a look. Thanks!

**Comment by rollbear** [comment]
This is awesome. Thank you!

**Pull request merged**
