### PR TITLE
Various documentation updates

### PR DESCRIPTION
**Pull request by rcdailey**
I have made a few various changes in this branch. I have separated each change into its own commit. However, to make the PR process easier, I have put them all up for review here. If any items are not acceptable or need more careful discussion, I'm happy to pull them out into separate PRs on request.

Summary of some changes I made:

* Ignore patterns were not sufficient, especially on Windows, so I made use of gitignore.io to generate some ignore patterns. The patterns specific to Trompeloeil were kept (they are at the bottom). The top portion can be replaced (upgraded) in the future as needed.
* A `.gitattributes` file was missing. I added it for proper EOL handling on Windows that doesn't depend on user's Git settings (repository now enforces EOL rules which will get you cleaner & more consistent PRs in the future).
* I added `.vscode` settings file that defines a few language-specific formatting rules for Markdown files. In the future, anyone using VS code to edit, format, and preview `*.md` file edits can benefit from this workspace configuration.
* I added some changes for #131 in the last commit.

### CODE REVIEW

**Comment by AndrewPaxie** [comment]
Thanks for this.  The `.gitattributes` and `.gitignore` files will help with
development that takes place on Windows hosts.

I also use VSCode, but mostly on Linux.  Visual Studio Community 2019
(current and preview releases) are my preferences on Windows.

When working with Markdown, I rely on the following extensions:

[markdownlint](
  https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint
) (0.26.0) and [Markdown Preview Enhanced](
  https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced
) (0.3.13).

My `settings.json` file includes the following configuration for
`markdownlint`:

```json
{
    "markdownlint.config": {
        "MD013": false,
        "MD024": false,
        "MD025": false,
        "MD026": {
            "punctuation": ".,;:!"
        },
        "MD033": {
            "allowed_elements": ["a"]
        }
    }
}
```

### Explanation

- [`MD013`](
  https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md013
  ): Ignore line length.  This might be dropped when 80 characters is normal
  for our `.md` files.
- [`MD024`](
  https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md024
  ): Allow duplicate headings.
- [`MD025`](
  https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md025
  ): Allow multiple top-level headings.
- [`MD026`](
  https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md026
  ):  Allow trailing `?` in heading.
- [`MD033`](
  https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md033
  ): Allow anchor inline HTML in documents.

This seems to be a good balance for the Trompeloeil documentation.

A future extension to Travis (or another CI server) builds, discussed
informally in the past, is to run `markdownlint` as a job on the Trompeloeil
documentation.  I would like to tackle this after more pressing `cmake`
improvements have been completed.

The documentation changes look good BTW.

**Comment by rollbear** [comment]
Typing on my phone, so very brief.

On .gitignore: By default the CLion IDE creates cmake-build-* directories in the project root, so that's the reason for them being ignored. It also stores settings under a .idea directory, which should also be ignored https://rider-support.jetbrains.com/hc/en-us/articles/207097529-What-is-the-idea-folder-

Never mind the Travis failures, they're caused by something else. 

I like the doc update.

**Comment by rcdailey** [comment]
> Typing on my phone, so very brief.
> 
> On .gitignore: By default the CLion IDE creates cmake-build-* directories in the project root, so that's the reason for them being ignored. It also stores settings under a .idea directory, which should also be ignored https://rider-support.jetbrains.com/hc/en-us/articles/207097529-What-is-the-idea-folder-
> 
> Never mind the Travis failures, they're caused by something else.
> 
> I like the doc update.

Thanks for the info. gitignore.io has a filter for CLion as well. I have added that to the gitignore file. If there are any other pieces of tech, we can add more as needed.

Note on CLion (or IntelliJ IDEs in general): Not all files under `.idea` should be ignored. I think it depends on the fork of intellij, but Android Studio for example puts some meaningful stuff under that directory that is worth versioning. I'm sure CLion has the same (although I have not personally used it). Based on the output from gitignore.io, it seems like they selectively ignore stuff they know you shouldn't commit:

```
# User-specific stuff
.idea/**/workspace.xml
.idea/**/tasks.xml
.idea/**/usage.statistics.xml
.idea/**/dictionaries
.idea/**/shelf

# Generated files
.idea/**/contentModel.xml

# Sensitive or high-churn files
.idea/**/dataSources/
.idea/**/dataSources.ids
.idea/**/dataSources.local.xml
.idea/**/sqlDataSources.xml
.idea/**/dynamic.xml
.idea/**/uiDesigner.xml
.idea/**/dbnavigator.xml

# Gradle
.idea/**/gradle.xml
.idea/**/libraries
```

That's just part of it. There's more, if you want to dig into the file.

**Comment by rcdailey** [comment]
@AndrewPaxie I was inspired by your detailed explanation of the linting settings. So I have done a few things:

* Added the linting configuration to the `.vscode/settings.json` file. I have made some adjustments to what you mentioned, which I will go over later.
* I added `docs/Contributing.md` to outline, at least for now, the documentation style recommendations. I'd like it if you could go over that documentation and let me know what is true or incorrect for this project. I did my best to deduce a consistent style based on what is already there. The goal of this file is to make PRs go smoother in the future since there will be less question on style and formatting.

The linting configuration I added is:

```json
"markdownlint.config": {
    "line-length": {
        "code_blocks": false,
        "tables": false
    },
    "ul-style": {
        "style": "asterisk"
    },
    "no-duplicate-heading": false,
    "no-trailing-punctuation": {
        "punctuation": ".,;:!"
    },
    "no-inline-html": {
        "allowed_elements": [
            "br"
        ]
    }
},
```

Differences from your list:

* The line length limit is not completely ignored (only for code blocks and tables). Now that the line length is specified in vs code settings *and* documented clearly in the Contributing.md file, I think it's reasonable to expect at least that written paragraphs are properly wrapped.
* Unordered list style uses asterisks. Most of the existing documentation uses hyphens, but I will fix these up later for you. I have to admit that I'm a bit partial to asterisks, and certain tooling (such as Markdown All in One extension) inserts asterisks by default for generated ToC. If you both prefer hyphens, I can change it to this. However I feel in most open source projects, the defacto go-to list style uses asterisks. So my initial attempt is to see if we can standardize on this.
* I didn't completely disable trailing punctuation checks for headers. Instead, I just allow `?` for your FAQ. I haven't seen any place where other characters must be allowed.
* `<br>` is the only HTML element allowed. Personally one of the markdown rules I hate the most is that they have functional behavior attached to trailing whitespace. Specifically, leaving 2 spaces at the end of a line means `<br>`. However, all of the tooling I use automatically strips trailing whitespace. Most of the time you shouldn't want it, IMHO. I think a better alternative is `<br>`, that way it's communicated more clearly that you intend a hard break, versus whitespace which I think should never be used for syntax. You'll also notice that I don't allow `<a>`. the *Markdown All in One* VS Code extension allows automatic ToC generation. You will see that I also use this in the Contributing.md document. IMHO, doing ToC by hand is error prone and a maintenance burden. Assuming everyone is OK with using VS Code to edit Markdown files, I think we can take advantage of this really cool extension to simplify the work of updating documentation.

Note that I've got another PR I will put up after this one is merged that contains refactored versions of Cookbook.md and README.md that follow the new linting rules. On my side, these files have 0 lint violations. I didn't include those changes here because they are quite big and I didn't want to keep making this PR bigger, for sanity reasons.

I plan to go over the other MD files as well and refactor them. I liked that you mentioned running markdownlint on the server side. I think this is a great idea. Since you guys are busy with the CMake stuff, I don't mind making that possible in parallel.

**Comment by rollbear** [comment]
I have mixed feelings about storing IDE metadata in the git repo. I can see the usefulness, at least if it can be trusted to be reasonable stable over time, but I cannot help feeling that since it's not the source code, it doesn't really belong there. Meta data used by linters in the CI is another thing, since it becomes part of the build process.

**Comment by rcdailey** [comment]
I've heard arguments for no projects in VCS but they don't hold any water to me. Granted, it's your project and you can do what you want, but I don't see any reasons to just pointlessly avoid committing helpful project state. I mean, line endings are a good example: By encouraging the usage of certain tooling to enforce your project coding standards, you make contributions much easier. You make pull requests more streamlined.

The alternative? Tons more documentation, more responsibility on the contributor of a pull request, and more time spent in a pull request nit-picking on whitespace stuff, line ending stuff. More questions and wasted time on what your expectations are.

In a professional environment especially, it's extremely important to commit stuff that's not workstation-specific and helps streamline the coding standards, formatting and style expectations on the team.

Also to be fair, VS Code isn't an IDE, at least I haven't seen it sold that way. It's just a general purpose text editor with some plugins. You could certainly use it like an IDE if you wanted. But based on what I've proposed so far, it's not being treated that way. What you see here isn't enforcing a project structure, it's not building anything. For now all we're opening the door for is using a particular editor to standardize style (column width) and interactive linting rules (as opposed to linting rules used in a post-processing fashion (e.g. a travis check for making sure lint rules are enforce).

Honestly if you give users the ability to "lint as they type", this is more productive than them being unaware of a mistake, and getting all the way through submitting a PR and getting build feedback, only to find out much later. It is less work the sooner you find issues.

Anyway I'll stop rambling. I've said all the reasons I can think of to convince you, but ultimately it's your call. I can tell you that I personally would be less likely to contribute in the future if there wasn't a tool to guide me to making that easier. That's the whole reason I spent my personal time to set this up for you, so it makes it easier for the next person.

Thanks for your feedback!

**Comment by rcdailey** [comment]
@rollbear Would love to continue the discussion. Please let me know your thoughts after reading my last response, when you get the time. Much appreciated.

**Comment by rollbear** [comment]
Apologies for seemingly falling off the edge of the world.

To speed things up, could you split this PR into a few parts.

The doc fix is a no brainer.

Fixups to allow doc markup linting is a no brainer.

Adding .gitignore stuff to avoid accidentally committing stuff from VS or VSCode, or other environments, is good.

Your argument for adding to git control stuff for various development environments makes me feel amazingly uneasy, but let's move that to a separate issue instead of letting this stall the stuff we all agree on is good.

**Comment by rcdailey** [comment]
@rollbear Sorry it took me a while to get back to this. I have removed the concerning changes, I will open another PR for discussion there. Thanks for your feedback.

**Comment by rcdailey** [comment]
@rollbear It's been a few months now, could I get a merge? I removed the stuff you were concerned with, as requested.

**Comment by rollbear** [comment]
You're right. Apologies. I think I've been more over worked than I've understood, and really needed some time away.

**Pull request merged**
