### PR TITLE
Fix streamer for input-range like types

### PR DESCRIPTION
**Pull request by DNKpp**
As discussed #313

### CODE REVIEW

**Comment by DNKpp** [comment]
Ah, lovely. Will try to fix that :)

**Comment by rollbear** [comment]
If you want to use them, the docker containers with the various compilers are available at ghcr.io/rollbear/gcc and ghcr.io/rollbear/clang, e.g. `docker pull ghcr.io/rollbear/gcc:4.9`. See https://github.com/rollbear/ci_compilers/ for info on how to use them. Be careful with using them for other purposes - I change them randomly for whatever reason.

**Comment by DNKpp** [comment]
Well, thanks. Hopefully it's working now. Never thought, that such a trivial code will be broken on c++11 conforming compilers.

**Comment by rollbear** [comment]
Yeah, trying to get something to work with such a wide range of compilers of various ages can be quite challenging. Thank you so much for this fix.

**Pull request merged**
