### PR TITLE
CI Improvements

### PR DESCRIPTION
**Pull request by Neargye**
Example of how I would like to improve ci. This is a dump of my experience, so that you can make a review and add criticism or suggestions.

ChangeLog:

* Merge master
* Add *build* to gitignore (ci use "build" folder)
* Replacing own testing scripts to cmake ctest
* Updated unit test framework to Catch 2.2.2.
* Warning as error for msvc
* Debug/Release configuration for msvc (test cases as in https://github.com/rollbear/trompeloeil/issues/69)
* kcov more for test, using only on Linux
* Clean-up
* Add more compiler image for ci (clang3.5, clang3.6 in readme says work with it, update xcode image)
* Add parallel build travis

### CODE REVIEW

**Comment by Neargye** [comment]
I can not understand why coverage became less

**Comment by rollbear** [comment]
I'm guessing it's the extra try/catch that adds a few lines which aren't covered.

**Comment by Neargye** [comment]
Just in case, may be add xcode8.0-8.3 and xcode9.0-9.3, not only xcode8/xcode9.

**Comment by Neargye** [comment]
Like to implement all that I wanted.

**Comment by Neargye** [comment]
Do I need to add testing with the flag C++17?

**Comment by AndrewPaxie** [comment]
I agree with @rollbear that we have to resolve #94 strictly before considering
additional build configurations.

I am working with @rollbear to define the build configurations
this project is to support in Travis-CI and AppVeyor.  This is to establish
a context for your work, a "bigger picture".  While I feel sure we will
eventually compile in AppVeyor a build with C\+\+ language standard 
set to `/std:c++17` I prefer requirements before implementation.

**Comment by Neargye** [comment]
The behavior of result `check_errors.sh` is the same as in the main branch.

I can comment on each change a little later.

**Comment by Neargye** [comment]
I'll first add testing different versions different C++.
Then compile clang with both -std=libc++ and -std=libstdc++.
Is there anything else that should be added?

I will also prepare a description of all the changes.

**Comment by rollbear** [comment]
Cool. Thanks. I can't think of anything else that is missing, right now.

**Comment by AndrewPaxie** [comment]
#### Recent changes to master

When you next merge in `master` you will find that

- Catch version has advanced to 2.2.3.
- Enabled destructor override warning in self_test build
  for Clang 5.0 or later.

Both affect the code in `CMakeLists.txt`.

#### Current build configurations

This table summarizes what Trompeloeil documents as supported
in the file `README.md` compared to what Travis actually builds
to confirm behaviour,

```text
            Supported in  Built with
            README.md?    using Travis?   Notes
Clang
3.5         Y             N
3.6         Y             N
3.7         Y             Y
3.8         Y             Y
3.9         Y             Y
4           Y             Y
5           Y             Y
6           Y             Y

XCode
xcode 7.3   -             Y
xcode 8     -             Y
xcode 9     -             Y

GCC
4.8.4+      Y             Y
4.9.3+      Y             Y
5           Y             Y
6           Y             Y
7           Y             Y
8           Y             Y

Visual Studio
2015        Y             N               Supported in AppVeyor
2017        Y             N               Supported in AppVeyor
```

#### Goals

It is good to see `clang++-3.5` and `clang++-3.6` will now be
supported in Travis.

Your plan of action is generally sound: start with existing compilers
and expand their modes.  Then add different standard libraries.
It is important to note that `g++` supports `libc++` and so is
to be a supported configuration.

For the builds performed in Travis (`g++`/`clang`) the
build configuration is basically summarized with a triplet,
`(compiler, language-standard, standard-library)`.

To give an idea of the scope, I have drawn up this table of the
compiler, mode, and library configurations we would like to test.
Each line is a separate job.

##### Target build configurations

```text
                Language    Standard
Compiler        Standard    Library     Travis    Comments
----------      --------    --------    -------   --------
g++-4.8         c++11       stdc++      Yes

g++-4.9         c++11       stdc++          New
g++-4.9         c++11       c++             New
g++-4.9         c++14       stdc++      Yes
g++-4.9         c++14       c++             New

g++-5           c++11       stdc++          New
g++-5           c++11       c++             New
g++-5           c++14       stdc++      Yes
g++-5           c++14       c++             New
g++-5           c++17       stdc++          New
g++-5           c++17       c++             New

g++-6           c++11       stdc++          New
g++-6           c++11       c++             New
g++-6           c++14       stdc++      Yes
g++-6           c++14       c++             New
g++-6           c++17       stdc++          New
g++-6           c++17       c++             New

g++-7           c++11       stdc++          New
g++-7           c++11       c++             New
g++-7           c++14       stdc++      Yes
g++-7           c++14       c++             New
g++-7           c++17       stdc++          New
g++-7           c++17       c++             New

g++-8           c++11       stdc++          New
g++-8           c++11       c++             New
g++-8           c++14       stdc++      Yes
g++-8           c++14       c++             New
g++-8           c++17       stdc++          New
g++-8           c++17       c++             New
g++-8           c++2a       stdc++          New
g++-8           c++2a       c++             New

clang++-3.5     c++11       stdc++ v7       New
clang++-3.5     c++14       stdc++ v7       New

clang++-3.6     c++11       stdc++ v7       New
clang++-3.6     c++11       c++             New
clang++-3.6     c++14       stdc++ v7       New
clang++-3.6     c++14       c++             New

clang++-3.7     c++11       stdc++ v7       New
clang++-3.7     c++11       c++             New
clang++-3.7     c++14       stdc++ v7   Yes
clang++-3.7     c++14       c++             New

clang++-3.8     c++11       stdc++ v7       New
clang++-3.8     c++11       c++             New
clang++-3.8     c++14       stdc++ v7   Yes       sanitize, lib version?
clang++-3.8     c++14       c++             New

clang++-3.9     c++11       stdc++ v8       New
clang++-3.9     c++11       c++             New
clang++-3.9     c++14       stdc++ v8   Yes       sanitize, lib version?
clang++-3.9     c++14       c++             New

clang++-4.0     c++11       stdc++ v8       New
clang++-4.0     c++11       c++             New
clang++-4.0     c++14       stdc++ v8   Yes       sanitize, lib version?
clang++-4.0     c++14       c++             New

clang++-5.0     c++11       stdc++ v8       New
clang++-5.0     c++11       c++             New
clang++-5.0     c++14       stdc++ v8   Yes       sanitize, lib version?
clang++-5.0     c++14       c++             New
clang++-5.0     c++17       stdc++ v8       New
clang++-5.0     c++17       c++             New
clang++-5.0     c++2a       stdc++ v8       New
clang++-5.0     c++2a       c++             New

clang++-6.0     c++11       stdc++ v8       New
clang++-6.0     c++11       c++             New
clang++-6.0     c++14       stdc++ v8   Yes       sanitize, lib version?
clang++-6.0     c++14       c++             New
clang++-6.0     c++17       stdc++ v8       New
clang++-6.0     c++17       c++             New
clang++-6.0     c++2a       stdc++ v8       New
clang++-6.0     c++2a       c++             New
```

Current jobs: 12.
New jobs: 57.
Total jobs: 69.
(All tallies exclude `Xcode`.)

The value of "Language Standard" is one of

- `c++11`: Compiler mode `-std=c++11`.
- `c++14`: Compiler mode `-std=c++14`.
- `c++17`: Compiler mode `-std=c+=17`.
- `c++2a`: Compiler mode `-std=c++2a`.

The value of "Standard Library" is one of

- `stdc++`: GCC `libstdc++-v3` for the given compiler version.
- `stdc++ v7`: GCC `libstdc++-v3` shipped in GCC 7.x.x.
- `stdc++ v8`: GCC `libstdc++-v3` shipped in GCC 8.x.x.
- `c++`: `libc++` from the LLVM project
  (`libc++-dev` `6.0-2` on Bionic Beaver).

There are two versions of `libstdc++-v3` mentioned as
Clang 3.5, 3.6, 3.7, and 3.8 compilers cannot use the GCC 8.0.1
`libstdc++-v3`.  They don't implement the builtin `__is_assignable`.
Therefore they must compile with a pre-GCC 8.0.1 standard library.

These combinations are excluded,

```text
                Language    Standard
Compiler        Standard    Library     Comment
----------      --------    --------    -------
g++-4.8         c++14       N/A         Compiler does not support C++14.
g++-4.8         c++11       c++         Complier cannot compile libc++.

clang++-3.5     c++11       c++
clang++-3.5     c++14       c++
```

Special builds that include sanitizers,

```text
                Language    Standard
Compiler        Standard    Library     Comment
----------      --------    --------    -------
g++-8           c++11       stdc++      -fsanitize=address,undefined

g++-8           c++14       stdc++      -fsanitize=address,undefined

clang++-6.0     c++11       c++         -fsanitize=address,undefined
                                        -fsanitize-address-use-after-scope

clang++-6.0     c++14       c++         -fsanitize=address,undefined
                                        -fsanitize-address-use-after-scope
```

#### `run_all_compiling_tests.sh` script

To help you towards this goal I have attached a script,
`run_all_compiling_tests.sh`, which I have been running
locally to regression test code changes before commit.
(I had to give it a `.txt` suffix so it could be uploaded.)

It does more than what we want Travis/cmake to do, namely it also tests
using `g++-latest` and `clang++-latest`.  It also tests Trompeloeil
with the sanitizers in one build configuration for each compiler,
`g++-8` (all modes) with `libstdc++-v3` and
`clang++-6.0` (all modes) with `libc++`.

I have also attached a file, `compiling_tests_command_lines.txt`,
which is the output of `run_all_compiling_tests.sh` without
actually invoking the compiler or running the unit tests.

It would be cool if I could use the `cmake`-derived build scripts
as the core of the script with a configuration command line as
simple as

```text
cmake \
-DCMAKE_BUILD_TYPE=Debug \
CXX=${compiler} \
CXX_STANDARD=${mode} \
CXX_LIBRARY=${library} \
SANITIZE=${sanitize}
```

followed by the build command and the run command.

#### Non-goals

Make expanding AppVeyor support a separate issue.
I am preparing a specification for this extended support
subsequently.  Please don't delete anything you have
done to AppVeyor configuration file as I will need it to
mine requirements.

#### Other points

I see you expanded the number of JOBS to various command lines.
From a recent set of build logs, it appears to me that about 50%
of the execution time of a job is spent downloading and installing
packages.  For example in this build for `clang++-5.0`,
<https://travis-ci.org/AndrewPaxie/trompeloeil/jobs/397661285>,
297 seconds of were spent in `apt-get` of these packages:
`g++-6`, `clang-5.0`, `libcurl4-openssl-dev`, `libelf-dev libdw-dev`
Elapsed time was 9m 50s (590 seconds).  Could this time be reduced
by enabling some form of caching in Travis?
This will become especially important when we expand the number
of jobs considerably.

I leave the specification of Xcode configurations to you.
I have no experience with these compilers let alone what
compiler flags they might accept
(mode, supported standard libraries).

#### Attachments

[run_all_compiling_tests.sh.txt](https://github.com/rollbear/trompeloeil/files/2195703/run_all_compiling_tests.sh.txt)
[compiling_tests_command_lines.txt](https://github.com/rollbear/trompeloeil/files/2195704/compiling_tests_command_lines.txt)

**Pull request closed without merging**
