### PR TITLE
Add a generator very closely based on gmock generator v1.8

### PR DESCRIPTION
**Pull request by ajpenner**
This code is mostly copied from gmock v1.8 with some of the modifications to allow for modern nested namespaces. 

The primary changes have been around replacing
MOCK_METHODn ->MAKE_MOCKn
MOCK_CONST_METHODn -> MAKE_CONST_MOCKn

The resulting file is dumped to stdout, and contains the headers:
#include <trompeloeil.hpp>
#include "<interface file>"

Some more includes may be needed for the mock to compile, but this script should remove much of the necessary grunt work behind making the mock object

### CODE REVIEW

**Comment by ajpenner** [comment]
The failure encountered is confusing. I did not make any C++ changes to the repo yet a C++ test is failing

**Comment by rollbear** [comment]
That error is caused by a spurious timeout in one of the apple xcode builds. Never mind it. It's not caused by your change.

I'm working on rewriting the CI pipeline to use GitHub actions, which is far more reliable, and faster too. I'm queueing this PR behind that job, so it will be a few days before I can return to you. I hope that's OK.

**Comment by ajpenner** [comment]
> That error is caused by a spurious timeout in one of the apple xcode builds. Never mind it. It's not caused by your change.
> 
> I'm working on rewriting the CI pipeline to use GitHub actions, which is far more reliable, and faster too. I'm queueing this PR behind that job, so it will be a few days before I can return to you. I hope that's OK.

No problem, I am glad to see a resolution is in the works 👍

**Comment by ajpenner** [comment]
bump

**Comment by rollbear** [comment]
I had to think hard about this one.

I like what you have done, and I like seeing such a tool being easily available, however, I do not think it belongs in this repo.I encourage you to make the generator available in your own repo, and I will gladly link to it, announce it and recommend it. I also recommend that you make (or encourage someone else to make) a Conan package for it.

**Pull request closed without merging**
