### PR TITLE
AppVeyor support

### PR DESCRIPTION
**Pull request by AndrewPaxie**
Implement #83.

### CODE REVIEW

**Comment by rollbear** [comment]
I think it'd be good to add an AppVeyor badge to README.md, just like there's one for travis-ci.

I wish I knew CMake better. I can't help but feel that `CMakeLists.txt` is becoming messy. This won't keep me from accepting the PR, btw, it's just an observation.

**Comment by AndrewPaxie** [comment]
This is my first `cmake` project and also know there must better code than what I've currently added to `CMakeLists.txt`.

I'm not sure I can add an AppVeyor badge until the `rollbear/trompeloeil` project is enabled.
Do we need an API token to get the badge?

**Comment by rollbear** [comment]
I have no idea what it takes to place a badge on README.md, but I think it'd be good to get one there.

**Comment by Neargye** [comment]
@rollbear why not place near travis badge?

**Comment by rollbear** [comment]
I think it should be near the travis-ci badge, @Neargye

**Comment by AndrewPaxie** [comment]
I'll enable AppVeyor integration first, then place the badge to the immediate right of the Travis badge.
It will report the build state of the `master` branch.
Should be up in the next 24 hours.

**Comment by AndrewPaxie** [comment]
AppVeyor badge added.

**Pull request merged**
